data_ori <- read.table("household_power_consumption.txt", header=T, sep=";", na.strings = "?")
da1 <- subset(data_ori, Date %in% c("1/2/2007", "2/2/2007"))
da1$DateTime <- paste(da1$Date, da1$Time)
da1$DateTime <- strptime(da1$DateTime, "%d/%m/%Y %H:%M:%S")
png(filename = "plot4.png", width=480, height=480, units="px")
par(mfcol=c(2,2))
plot(da1$DateTime, da1$Global_active_power, type="l", xlab="", ylab="Global Active Power (killowatts)")
plot(da1$DateTime, da1$Sub_metering_1, type="l", col="black", xlab="", ylab="Energy sub metering")
with(da1, points(DateTime, Sub_metering_2, col="red", type="l"))
with(da1, points(DateTime, Sub_metering_3, col="blue", type="l"))
legend("topright", lty=1, col=c("black","red", "blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
plot(da1$DateTime, da1$Voltage, type="l",xlab="datatime", ylab="Voltage")
plot(da1$DateTime, da1$Global_reactive_power, type="l",xlab="datatime", ylab="Global_reactive_power")
dev.off()
